infinitefire/IssueTrackingSystem

src/main/resources/application.properties
src/main/resources/templates/index.html
src/main/resources/templates/issue/form.html
src/main/resources/templates/issue/show.html
src/main/resources/templates/milestone/form.html
src/main/resources/templates/milestone/list.html
src/main/resources/templates/template.html
src/main/resources/templates/user/join.html
src/main/resources/templates/user/login.html

* template.html 생성
* head, navigation, container, footer 구조화

template 재사용을 위한 구조화

---

pom.xml
src/main/java/infinitefire/project/domain/User.java
src/main/java/infinitefire/project/domain/UserRepository.java
src/main/java/infinitefire/project/web/UserController.java
src/main/resources/templates/user/login.html
src/main/resources/templates/user/new.html

* user 생성 - /user/new (get)
* user 로그인/로그아웃 - /user/login (post), /user/logout (get)

 #12 User CRUD 기능 추가

---

pom.xml
src/main/java/infinitefire/project/domain/User.java
src/main/java/infinitefire/project/web/UserController.java
src/main/resources/templates/user/modify.html

* User 데이터 수정 HTML (user/modify.html)
* User 데이서 수정 기능 구현 (user/{id}/modify [GET, PUT])

#17 User 데이터 수정 HTML 추가 및 데이터 수정 기능 구현

---

src/main/java/infinitefire/project/domain/Issue.java
src/main/java/infinitefire/project/domain/User.java

객체 연관 관계 맵핑 및 메소드 오버라이딩

---

src/main/java/infinitefire/project/domain/Issue.java
src/main/java/infinitefire/project/domain/User.java
src/main/java/infinitefire/project/web/IssueController.java
src/main/resources/templates/issue/detail.html
src/main/resources/templates/issue/modify.html

Issue 수정,삭제 구현 완료

---

src/main/java/infinitefire/project/web/UserController.java
src/main/resources/templates/template.html
src/main/resources/templates/user/detail.html
src/main/resources/templates/user/login_error.html
src/main/resources/templates/user/modify.html

#30 User 정보 확인 페이지 & Login Error HTML 추가
* User 정보를 확인 할 수 있는 /user/detail.html 추가
* User 로그인 시 발생하는 에러 페이지 /user/login_error.html 추가

User 정보 확인 페이지 & Login Error HTML 추가

---

src/main/java/infinitefire/project/web/MilestoneController.java
src/main/resources/static/css/custom.css
src/main/resources/static/css/styles.css
src/main/resources/templates/milestone/detail.html
src/main/resources/templates/milestone/list.html
src/main/resources/templates/template.html

* footer layout 수정
* milestone detail 기능 구현

footer layout 수정 / milestone detail 기능 구현

---

src/main/java/infinitefire/project/web/UserController.java
src/main/resources/templates/user/login_require.html

#30 User 관련 접근 시 에러 HTML 추가
* login error, login require html 추가
* UserController 클래스 리팩토링

#30 User 관련 접근 시 에러 HTML 추가

---

src/main/java/infinitefire/project/ImsApplication.java
src/main/java/infinitefire/project/domain/UserState.java
src/main/java/infinitefire/project/storage/FileSystemStorageService.java
src/main/java/infinitefire/project/storage/StorageException.java
src/main/java/infinitefire/project/storage/StorageFileNotFoundException.java
src/main/java/infinitefire/project/storage/StorageProperties.java
src/main/java/infinitefire/project/storage/StorageService.java
src/main/java/infinitefire/project/web/FileUploadController.java
src/main/java/infinitefire/project/web/UserController.java
src/main/resources/import.sql
src/main/resources/templates/user/detail.html
src/main/resources/templates/user/new.html

* StorageService, FileSystemStorageService, StorageProperties, StorageException, StorageFileNotFoundException 추가
* User 회원가입 페이지에서 Image 첨부파일을 로컬에 Upload
* 로컬에 저장된 URL을 Database User 테이블에 적용 (수정예외)
* User 정보 확인 페이지에서 해당 이미지 표시 확인

User Profile Image Upload 구현

---

src/main/java/infinitefire/project/domain/User.java
src/main/java/infinitefire/project/storage/StorageService.java
src/main/java/infinitefire/project/web/FileUploadController.java
src/main/java/infinitefire/project/web/UserController.java

- * Uesr 회원 가입 시 Profile Image 미등록의 경우 기본 이미지 설정
- * User 회원 탈퇴 시 Profile Image 파일 제거
- * User 회원 탈퇴 시 Profile Image none.png로 변경

#63 User Profile Image 개선 작업

---

src/main/java/infinitefire/project/storage/StorageService.java
src/main/resources/application-local.properties
src/main/resources/application-server.properties
src/main/resources/application.properties

* Profile 파일 생성 (Local / Server)
* Profile Image와 COmment Attachment 파일의 경로 지정

#67 Profile 파일을 이용한 Local/Server 설정 관리

---

src/main/java/infinitefire/project/storage/FileExtensionUtils.java

* FileExtensionUtils Interface를 통해 확장자 관련 기능 구현

#85 Attachment Upload 구현

---

src/main/java/infinitefire/project/domain/User.java
src/main/java/infinitefire/project/web/CommentController.java
src/main/resources/static/js/main.js
src/main/resources/templates/issue/detail.html

*  main.js와 /issue/detail.html에서 해당 문제에 대한 원인을 파악 & 문제 해결

#89 Issue에 Comment, Assignee 생성 시 프로필 이미지 미표시 문제

---

src/main/java/infinitefire/project/web/UserController.java
src/main/resources/application.properties
src/main/resources/static/js/main.js
src/main/resources/templates/user/modify.html

* User 회원 정보 수정 시 발생 Error 해결
* 파일 업로드에 사용되는 Input type="file" 태그의 css를 MDL 디자인으로 변경 (modify.html)
* File upload 크기 제한 적용 (최대 3MB) / application.properties 변경
* input type="file"태그의 change event 구현 (main.js)

#101 Input type="file" 태그 MDL로 개선

---

src/main/java/infinitefire/project/web/UserController.java
src/main/resources/templates/template.html
src/main/resources/templates/user/mypage.html

* 기존의 MyPage 버튼 클릭 시 이동하는 modify.html 대신 회원 정보 수정과 회원 탈퇴 버튼이 추가된 mypage.html 추가 구현
* 상단의 ID와 Name 클릭 시에도 MyPage로 이동하도록 수정

#90 User MyPage 구현

---

src/main/java/infinitefire/project/web/UserController.java
src/main/resources/import.sql
src/main/resources/static/js/main.js
src/main/resources/templates/issue/detail.html

* 첨부파일 크기 3MB 체크 함수 리팩토링
* 댓글 생성과 수정 시의 태그들 id값 정리
* 댓글 정보 수정 부분 완료 (파일첨부 X, UI만 표시)
* hibernate db error (댓글에 관한 insert.sql insert 구문 삭제)

#85 Attachment Upload 구현 (부분완료)

---

src/main/resources/application-deploy.properties
src/main/resources/application-local.properties

- 현재 진행 사항 배포 테스트
- 프로젝트 진행 중 변경된 스키마 적용을 위한 application-deploy.properties 추가

#118 현재 진행 사항 배포 테스트 + application-deploy.properties 추가

---

src/main/java/infinitefire/project/web/OrganizationController.java
src/main/resources/templates/Organization/detail.html
src/main/resources/templates/index.html

* Group 정보 보기 organization/detail.html 추가

#94 Oranization의 기본 CRUD 구현

---

src/main/java/infinitefire/project/web/OrganizationController.java
src/main/resources/templates/Organization/detail.html

* Group 정보보기 기능 부분 구현 (그룹 정보, AssigneeList 표현)

#94 Organization 기능 개선 작업

---

src/main/java/infinitefire/project/domain/Issue.java
src/main/java/infinitefire/project/domain/Label.java
src/main/java/infinitefire/project/domain/Milestone.java
src/main/java/infinitefire/project/domain/Organization.java
src/main/java/infinitefire/project/web/IssueController.java
src/main/java/infinitefire/project/web/UserController.java

#54 Warning 제거

---

src/main/java/infinitefire/project/domain/Organization.java
src/main/java/infinitefire/project/web/MainController.java
src/main/resources/templates/index.html

* 로그인 한 유저의 Organization이 보이도록 변경

#126 Organization & Index Page 개선
